[package]
name = "rust-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "*"
aoc-runner-derive = { version = "*" }
bit-vec = "0.6"
regex = "1"
itertools = "0.9.0"
hex = "*"